//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnicaFrontEnd.WSAutos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSAutos.IAutos")]
    public interface IAutos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutos/ObtenerAutos", ReplyAction="http://tempuri.org/IAutos/ObtenerAutosResponse")]
        PruebaTecnica.Model.Auto[] ObtenerAutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutos/ObtenerAutos", ReplyAction="http://tempuri.org/IAutos/ObtenerAutosResponse")]
        System.Threading.Tasks.Task<PruebaTecnica.Model.Auto[]> ObtenerAutosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutosChannel : PruebaTecnicaFrontEnd.WSAutos.IAutos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutosClient : System.ServiceModel.ClientBase<PruebaTecnicaFrontEnd.WSAutos.IAutos>, PruebaTecnicaFrontEnd.WSAutos.IAutos {
        
        public AutosClient() {
        }
        
        public AutosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PruebaTecnica.Model.Auto[] ObtenerAutos() {
            return base.Channel.ObtenerAutos();
        }
        
        public System.Threading.Tasks.Task<PruebaTecnica.Model.Auto[]> ObtenerAutosAsync() {
            return base.Channel.ObtenerAutosAsync();
        }
    }
}
